# Locate udev
# This module defines
# UDEV_LIBRARY
# UDEV_FOUND, if false, do not try to link to ffmpeg
# UDEV_INCLUDE_DIR, where to find the headers
#

SET(UDEV_FOUND FALSE)

IF (NOT UDEV_INCLUDE_DIR)
  FIND_PATH(UDEV_INCLUDE_DIR NAMES libudev.h)
ENDIF (NOT UDEV_INCLUDE_DIR)

IF (NOT UDEV_LIBRARY)
  FIND_LIBRARY(UDEV_LIBRARY NAMES udev)
ENDIF (NOT UDEV_LIBRARY)

IF (UDEV_INCLUDE_DIR AND UDEV_LIBRARY)
  SET(UDEV_FOUND TRUE)
ENDIF (UDEV_INCLUDE_DIR AND UDEV_LIBRARY)
