.TH DFF "1" "February 2011" "dff version 0.9" "User Commands"
.SH NAME
dff \- A powerful, efficient and modular digital forensics tool.
.SH SYNOPSIS
.B dff
[\fIoptions\fR]
.SH DESCRIPTION
Digital Forensics Framework
.B dff
is a simple but powerful open source tool with a flexible module system which will help you in your digital forensics works, including files recovery due to error or crash, evidence research and analysis, etc. The source code is written in C++ and Python, allowing performances and great extensibility.

.SH OPTIONS
.TP
\fB\-v\fR      \fB\-\-version\fR
display current version
.TP
\fB\-g\fR      \fB\-\-graphical\fR
launch graphical interface
.TP
\fB\-t\fR      \fB\-\-test\fR=\fINAME\fR
start a specific test
.TP
\fB\-l\fR      \fB\-\-language\fR=\fILANG\fR
use \fILANG\fR as interface language, available: es, en, fr.
.TP
\fB\-h\fR,     \fB\-\-help\fR
display this help message
.TP
\fB\-d\fR,     \fB\-\-debug\fR
redirect IO to system console
.TP
        \fB\-\-verbose\fR=\fILEVEL\fR
set verbosity level when debugging, available \fILEVEL\fR: 0 to 3
.TP
\fB\-c\fR,     \fB\-\-config=\fIFILEPATH\fR
use config file from given \fIFILEPATH\fR
.TP
\fB\-b\fR,     \fB\-\-batch=\fIFILEPATH\fR
launch batch file at start (list of shell commands) from \fIFILEPATH\fR
.SH "SEE ALSO"
Project's wiki with up-to-date documentation for \fBdff\fR
is provided at this url: \fIhttp://wiki.digital-forensic.org/\fR.
.TP
Embeded help is also available through the \fIHelp\fR menu in \fBdff\fR.
